@HOST = http://localhost:8080/santa

### Compute a new draw

POST {{HOST}}/draws/

### List past draws

GET {{HOST}}/draws

### Get draw detail

GET {{HOST}}/draws/5

### List n latest draws

GET {{HOST}}/draws?latest=5
