# Generated by Django 5.0 on 2023-12-18 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0004_rename_history_drawhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ban',
            new_name='Exclusion',
        ),
        migrations.AlterField(
            model_name='drawhistory',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santa.draw'),
        ),
    ]
