# Generated by Django 5.0 on 2023-12-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0005_rename_ban_exclusion_alter_drawhistory_draw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrawHistory',
            new_name='DrawPair',
        ),
    ]
